# Generated by Django 3.2.20 on 2023-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reserved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
