# Generated by Django 3.2.20 on 2023-08-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_post_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reserved',
            new_name='reserve',
        ),
    ]
