# Generated by Django 3.2.20 on 2023-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_reserved_post_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='post',
            name='item_description',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
