# Generated by Django 3.2.20 on 2023-08-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20230828_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reserve',
        ),
        migrations.AddField(
            model_name='post',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
