# Generated by Django 3.2.20 on 2023-08-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20230828_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reserve',
            new_name='reserved',
        ),
    ]
