# Generated by Django 3.2.20 on 2023-08-28 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0013_rename_reserve_post_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reserved',
        ),
        migrations.AddField(
            model_name='post',
            name='reserve',
            field=models.ManyToManyField(blank=True, default='reserve', related_name='food_item_reserve', to=settings.AUTH_USER_MODEL),
        ),
    ]
