# Generated by Django 3.2.20 on 2023-08-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20230828_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reserve',
        ),
        migrations.AddField(
            model_name='post',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
