# Generated by Django 3.2.20 on 2023-08-30 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0015_auto_20230830_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reserve',
        ),
        migrations.AddField(
            model_name='post',
            name='reserve',
            field=models.ManyToManyField(blank=True, default='reserve', related_name='food_item_reserve', to=settings.AUTH_USER_MODEL),
        ),
    ]
