# Generated by Django 3.2.20 on 2023-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='post',
            name='item_description',
            field=models.TextField(max_length=60),
        ),
    ]
